version: '3'

services:
  db-postgres:
    container_name: teceo-db-desafio
    image: 'bitnami/postgresql:16.6.0'
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    volumes:
      - ../../data/pg:/data/postgres
